name: Automation Exercise Runner
on:
    pull_request:
        branches:
            - "master"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses:  actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
                node-version: 21
          - name: Install Dependencies
            run: npm install
          - name: Run Automation Exercise Suite
            env:
                HEADLESS_MODE: ${{secrets.HEADLESS_MODE}}
                PRODUCTION_MODE: ${{secrets.PRODUCTION_MODE}}
            run: npm run test:chrome
            